Repository dautroc/github-conventional-comments, pull requests merged in 2025-07, with the labels that each got.

#6 Fix: issue-suggestion click does not insert the corresponding text into the comment box
  src/main.ts
Labels: bug, good first issue

#15 Fix: ensure consistent keydown capture and focus behavior in new comment UI
  src/buttonHandler.ts
  src/inputHandler.ts
Labels: bug

#16 Enhancement: Enhance UX when clicking on options popup
  src/inputHandler.ts
Labels: enhancement

#18 Fix + Enahancement: Support button handler setting in new CodeReview UI
  src/buttonHandler.ts
  src/common.ts
  src/inputHandler.ts
  src/styles/styles.scss
  src/types.ts
Labels: enhancement

#27 Enhancement: enhance bang behavior
  src/inputHandler.ts
Labels: enhancement

#30 Fix: Fix popup auto close on clicking in "Review complete" comment box
  src/inputHandler.ts
Labels: bug

#33 Enhancement: Update manifest icons
  icons/icon128.png
  icons/icon16.png
  icons/icon19.png
  icons/icon32.png
  icons/icon38.png
  icons/icon48.png
  manifest.json
Labels: enhancement

#34 Fix: bang suggestion issue (suggestion popup doesn't disappear when typing)
  src/inputHandler.ts
Labels: bug
